import type { Metadata } from 'next';
import '@/infrastructure/config';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import { ThemeProvider } from '@/ui/theme-provider';
import 'reflect-metadata';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const container =
  'mx-auto w-full px-4 sm:px-6 lg:px-8 max-w-[95vw] 2xl:max-w-[1800px] my-4';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-Hant" suppressHydrationWarning>
      <body
        className={[
          geistSans,
          geistMono,
          'min-h-dvh bg-white text-slate-900 antialiased',
          'dark:bg-slate-950 dark:text-slate-100',
        ].join(' ')}
      >
        {/* 無障礙 Skip Link */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-slate-900 focus:px-3 focus:py-2 focus:text-white"
        >
          跳到主要內容
        </a>

        {/* Header / 導覽列 */}
        <header className="sticky top-0 z-40 border-b border-slate-200/70 bg-white/70 backdrop-blur dark:border-slate-800 dark:bg-slate-950/60">
          <div className={container}>
            <nav className="flex h-16 items-center justify-between">
              <div className="flex items-center gap-3">
                <Link href="/" className="flex items-center gap-2">
                  <Image
                    width={28}
                    height={28}
                    src="/logo.png"
                    alt="Logo"
                    className="h-7 w-7 rounded-md shadow-sm"
                  />
                  <span className="text-xl font-bold tracking-tight">
                    Pokemon D3 Effect
                  </span>
                </Link>
              </div>

              <div className="hidden items-center gap-6 md:flex">
                <Link
                  href="/pokemon"
                  className="text-sm text-slate-600 hover:text-slate-900 dark:text-slate-300 dark:hover:text-white"
                >
                  寶可夢
                </Link>
                <Link
                  href="/chart"
                  className="text-sm text-slate-600 hover:text-slate-900 dark:text-slate-300 dark:hover:text-white"
                >
                  圖表
                </Link>
                <Link
                  href="https://github.com/krok1029/Pokemon-D3-Effect-Practice"
                  className="text-sm text-slate-600 hover:text-slate-900 dark:text-slate-300 dark:hover:text-white"
                >
                  GitHub
                </Link>
              </div>
            </nav>
          </div>
        </header>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* 主內容 */}
          <main id="main" className={container}>
            {children}
          </main>
        </ThemeProvider>
        {/* Footer */}
        <footer className="mt-16 border-t border-slate-200/70 py-8 dark:border-slate-800">
          <div className={container}>
            <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
              <p className="text-sm text-slate-500 dark:text-slate-400">
                © {new Date().getFullYear()} Pokemon D3 Effect. All rights
                reserved.
              </p>
              <div className="flex items-center gap-4 text-sm">
                <Link
                  href="/privacy"
                  className="text-slate-600 hover:text-slate-900 dark:text-slate-300 dark:hover:text-white"
                >
                  隱私權
                </Link>
                <Link
                  href="/terms"
                  className="text-slate-600 hover:text-slate-900 dark:text-slate-300 dark:hover:text-white"
                >
                  服務條款
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
